// Colors for use by helper.eventGenerator()
export const colors = [
  "#48a7a7",
  "#4885aa",
  "#c8b638",
  "#cb96a3",
  //"#ad96a4",
  "#407989",
];

// Card data for use by helper.cardGenerator()
export const EPCards = [
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
  {
    imgUrl: "/images/nathaniel-worrell-RmyH6CinwtM-unsplash.jpg",
    imgAlt: "A test image",
  },
];

// Event data for use by helper.eventGenerator()
export const events = [
  {  title: "Alzheimer's Disease in an Era of Treatment | Virtual Session" },
  {  title: "An Evening at Cabaret ZaZou" },
  {  title: "An Evening at the Chicago Symphony Orchestra" },
  {  title: "Annual Meeting" },
  {  title: "Arts & Culture and Nonprofit Sector Session" },
  {  title: "Book Club" },
  {  title: "Chicago Botanic Garden Lightscape" },
  {  title: "Corporate Sector Session" },
  {  title: "Emerita and Life Member Social Gathering & Lunch" },
  {  title: "Emerita Sector Gathering - Virtual" },
  {  title: "Ernest Shackleton Loves Me at Porchlight Theatre" },
  {  title: "Explore the Shedd Aquarium with Bridget C. Coughlin" },
  {  title: "Exploring the Stars with the Experts Through the James Webb Space Telescope" },
  {  title: "Fall Dinner" },
  {  title: "Financial Services Sector Session" },
  {  title: "Health, Science and Medicine Sector Session" },
  {  title: "Higher Education Sector Session" },
  {  title: "HistoryMakers with Julieanna Richardson" },
  {  title: "Holiday Reception Open House" },
  {  title: "Launchpad for Women Senior Leaders" },
  {  title: "Law and Government Sector Session" },
  {  title: "Media and Communications Sector Session" },
  {  title: "New Member Breakfast" },
  {  title: "Private Dinners " },
  {  title: "Professional Services & Associations, Mid-size Private Companies Sector Session" },
  {  title: "Sharing and Support Virtual Session" },
  {  title: "TCN New Member Breakfast" },
  {  title: "TCN's New Year's Celebration at the Art Institute" },
  {  title: "The Art of Watchmaking: Presented by Sandrine Donguy for Vacheron Constantin" },
  {  title: "The Conservation Center Private Tour & Reception" },
  {  title: "Villette at Lookingglass Theatre" },
  {  title: "Women in the Forefront Luncheon" },
  {  title: "Women on Boards" },
  {  title: "Workforce Solutions for Attracting and Retaining Talent in Challenging Industries" }
];

export const AMImages = [
  { imgUrl: "./images/annualmeetingpictures/AM1.webp", imgAlt: "" },
  { imgUrl: "./images/annualmeetingpictures/AM2.webp", imgAlt: "" },
  { imgUrl: "./images/annualmeetingpictures/AM3.webp", imgAlt: "" },
  { imgUrl: "./images/annualmeetingpictures/AM4.webp", imgAlt: "" },
  { imgUrl: "./images/annualmeetingpictures/AM5.webp", imgAlt: "" },
  { imgUrl: "./images/annualmeetingpictures/AM6.webp", imgAlt: "" }
];
export const WIFLImages = [
  { imgUrl: "./images/wifl/WIFL1.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL2.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL3.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL4.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL5.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL6.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL7.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL8.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL9.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL10.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL11.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL12.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL13.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL14.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL15.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL16.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL17.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL18.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL19.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL20.jpg", imgAlt: "" },
  { imgUrl: "./images/wifl/WIFL21.jpg", imgAlt: "" },
];

export const eventPics = [
  { imgUrl: "./images/Events/1.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/2.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/3.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/4.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/5.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/6.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/7.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/8.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/9.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/10.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/11.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/12.jpg", imgAlt: "" },
  { imgUrl: "./images/Events/13.jpg", imgAlt: "" }
];

export const logos = [
  {  imgAlt: "Access Living of Metropolitan Chicago",  imgUrl: "./images/EPLogos/Access Living.jpg" },
  {  imgAlt: "Altair",  imgUrl: "./images/EPLogos/altair.png" },
  {  imgAlt: "American Academy of Periodontology",  imgUrl: "./images/EPLogos/aap.jpg" },
  {  imgAlt: "American College of Healthcare Executives",  imgUrl: "./images/EPLogos/American College of Healthcare Executives logo.jpg" },
  {  imgAlt: "American Dental Association",  imgUrl: "./images/EPLogos/American Dental Association.png" },
  {  imgAlt: "American Society of Anesthesiologists",  imgUrl: "./images/EPLogos/American Society of Anesthesiologists.jpg" },
  {  imgAlt: "American Association of Diabetes Educators ",  imgUrl: "./images/EPLogos/aade.png" },
  {  imgAlt: "American College of Surgeons",  imgUrl: "./images/EPLogos/American College of Surgeons.png" },
  {  imgAlt: "American Medical Association",  imgUrl: "./images/EPLogos/ama.png" },
  {  imgAlt: "Ann and Robert H. Lurie Children's Hospital of Chicago",  imgUrl: "./images/EPLogos/Lurie Children-s Hospital.jpg" },
  {  imgAlt: "Aon",  imgUrl: "./images/EPLogos/1024px-Aon_Corporation_logo.png" },
  {  imgAlt: "Art Institute of Chicago",  imgUrl: "./images/EPLogos/AIC Color Logo-01.jpg" },
  {  imgAlt: "Association for Supply Chain Management",  imgUrl: "./images/EPLogos/ASCM.png" },
  {  imgAlt: "Association Forum",  imgUrl: "./images/EPLogos/Association Forum.jpg" },
  {  imgAlt: "AT Kearney",  imgUrl: "./images/EPLogos/AT Kearney.jpg" },
  {  imgAlt: "Azteca Foods Inc.",  imgUrl: "./images/EPLogos/azteca.png" },
  {  imgAlt: "Boys and Girls Clubs of Chicago",  imgUrl: "./images/EPLogos/boysGirlsClubs.png" },
  {  imgAlt: "BPI Group",  imgUrl: "./images/EPLogos/bpi.jpg" },
  {  imgAlt: "Capri Investment Group",  imgUrl: "./images/EPLogos/capri.png" },
  {  imgAlt: "Cara",  imgUrl: "./images/EPLogos/cara.jpg" },
  {  imgAlt: "Caroline Rose, Inc.",  imgUrl: "./images/EPLogos/CarolineRose.jpg" },
  {  imgAlt: "CCIM Institute",  imgUrl: "./images/EPLogos/CCIM.png" },
  {  imgAlt: "Chicago Children's Museum",  imgUrl: "./images/EPLogos/chicagoChildrensMuseum.jpg" },
  {  imgAlt: "Chicago Equity Partners",  imgUrl: "./images/EPLogos/ChicagoEquity.png" },
  {  imgAlt: "Chicago Public Media",  imgUrl: "" },
  {  imgAlt: "City Tech Collaborative",  imgUrl: "./images/EPLogos/cityTech.png" },
  {  imgAlt: "Cook County Board of Commissioners",  imgUrl: "./images/EPLogos/cookCounty.jpg" },
  {  imgAlt: "Cotter Consulting",  imgUrl: "./images/EPLogos/Cotter Logo.jpg" },
  {  imgAlt: "Cushman & Wakefield",  imgUrl: "./images/EPLogos/cushman.jpg" },
  {  imgAlt: "Dentons US LLP",  imgUrl: "./images/EPLogos/dentons.jpg" },
  {  imgAlt: "Discover Financial Services",  imgUrl: "./images/EPLogos/discover.jpg" },
  {  imgAlt: "Dominican University",  imgUrl: "./images/EPLogos/dominican.png" },
  {  imgAlt: "DS Economics",  imgUrl: "" },
  {  imgAlt: "DuSable Museum",  imgUrl: "" },
  {  imgAlt: "Easterseals",  imgUrl: "./images/EPLogos/easterseals.png" },
  {  imgAlt: "Economic Club of Chicago ",  imgUrl: "./images/EPLogos/econclub.png" },
  {  imgAlt: "Edward-Elmhurst Healthcare",  imgUrl: "./images/EPLogos/edward-elmhurst.png" },
  {  imgAlt: "Errand Solutions, LLC",  imgUrl: "./images/EPLogos/errandsolutions.png" },
  {  imgAlt: "Fluresh LLC",  imgUrl: "./images/EPLogos/fluresh.png" },
  {  imgAlt: "Foley & Lardner LLP",  imgUrl: "./images/EPLogos/Foley-LLP-Blue.jpg" },
  {  imgAlt: "Forward Space",  imgUrl: "./images/EPLogos/forwardspace.jpg" },
  {  imgAlt: "Friend Health",  imgUrl: "./images/EPLogos/friendhealth.png" },
  {  imgAlt: "Governors State University",  imgUrl: "./images/EPLogos/governorsstate.png" },
  {  imgAlt: "Graham Foundation for Advanced Studies in Fine Arts",  imgUrl: "./images/EPLogos/gf.jpg" },
  {  imgAlt: "Graham Media Group",  imgUrl: "./images/EPLogos/grahammediagroup.jpg" },
  {  imgAlt: "Grainger",  imgUrl: "./images/EPLogos/grainger.jpg" },
  {  imgAlt: "Grant Thornton LLP",  imgUrl: "./images/EPLogos/grantthornton.png" },
  {  imgAlt: "Greater Chicago Food Depository",  imgUrl: "./images/EPLogos/gcfd.jpg" },
  {  imgAlt: "Hadley Institute for the Blind and Visually Impaired",  imgUrl: "./images/EPLogos/hadley.jpg" },
  {  imgAlt: "Health Hippo",  imgUrl: "./images/EPLogos/healthhippo.png" },
  {  imgAlt: "Heartland Alliance",  imgUrl: "./images/EPLogos/heartlandalliance.jpg" },
  {  imgAlt: "IDEX Corporation",  imgUrl: "./images/EPLogos/idex.png" },
  {  imgAlt: "Illinois Medical District",  imgUrl: "./images/EPLogos/ilmedicaldistrict.png" },
  {  imgAlt: "Institute of Food Technologists",  imgUrl: "./images/EPLogos/Institute of Food Technologists.jpg" },
  {  imgAlt: "Isobar",  imgUrl: "./images/EPLogos/isobar.jpg" },
  {  imgAlt: "J.B. and M.K. Pritzker Family Foundation",  imgUrl: "./images/EPLogos/pritzker.png" },
  {  imgAlt: "Junior Achievement of Chicago",  imgUrl: "./images/EPLogos/JuniorAcheivement.png" },
  {  imgAlt: "KDM Engineering",  imgUrl: "" },
  {  imgAlt: "Kellogg Company",  imgUrl: "./images/EPLogos/Kellogs.png" },
  {  imgAlt: "Koya Leadership Partners",  imgUrl: "./images/EPLogos/Koya.png" },
  {  imgAlt: "KPMG",  imgUrl: "./images/EPLogos/KPMG.jpg" },
  {  imgAlt: "Latino Policy Forum",  imgUrl: "./images/EPLogos/LPF Logo.JPG" },
  {  imgAlt: "LEAP Innovations",  imgUrl: "./images/EPLogos/LEAP.png" },
  {  imgAlt: "Lincoln Park Zoo ",  imgUrl: "./images/EPLogos/Lincoln Park Zoo.png" },
  {  imgAlt: "Lurie Children's Hospital",  imgUrl: "./images/EPLogos/Lurie logo.jpg" },
  {  imgAlt: "Mann Weitz & Associates LLC",  imgUrl: "./images/EPLogos/MWA.jpg" },
  {  imgAlt: "Marsh",  imgUrl: "./images/EPLogos/MArsh.jpg" },
  {  imgAlt: "Medical Home Network",  imgUrl: "./images/EPLogos/MHN_logo.png" },
  {  imgAlt: "Mercer",  imgUrl: "./images/EPLogos/0026.png" },
  {  imgAlt: "Morgan Stanley",  imgUrl: "./images/EPLogos/MS_Logo-13p0_K.png" },
  {  imgAlt: "Morningstar",  imgUrl: "./images/EPLogos/Morningstar.png" },
  {  imgAlt: "MxD",  imgUrl: "./images/EPLogos/MD.png" },
  {  imgAlt: "Navigant Consulting Inc.",  imgUrl: "./images/EPLogos/Navigant_Logo.jpg" },
  {  imgAlt: "Navy Pier",  imgUrl: "./images/EPLogos/Navy Pier.png" },
  {  imgAlt: "Neiman Brothers",  imgUrl: "./images/EPLogos/Neiman Brothers logo.jpg" },
  {  imgAlt: "NextLevel Health Illinois",  imgUrl: "./images/EPLogos/nextlevelhealth.png" },
  {  imgAlt: "Northwestern University",  imgUrl: "./images/EPLogos/northwestern.jpg" },
  {  imgAlt: "Optima, Inc.",  imgUrl: "./images/EPLogos/optima.jpg" },
  {  imgAlt: "Primera Engineers",  imgUrl: "./images/EPLogos/primera.jpg" },
  {  imgAlt: "r-barc",  imgUrl: "./images/EPLogos/rbarc.jpg" },
  {  imgAlt: "Robinson Hill, Inc.",  imgUrl: "./images/EPLogos/robinsonhill.jpg" },
  {  imgAlt: "School of The Art Institute",  imgUrl: "./images/EPLogos/saic.jpg" },
  {  imgAlt: "Society of Actuaries",  imgUrl: "./images/EPLogos/Society of Actuaries.jpg" },
  {  imgAlt: "The Lamar Johnson Collaborative",  imgUrl: "./images/EPLogos/Lamar Johnson.png" },
  {  imgAlt: "The Northridge Group, Inc.",  imgUrl: "./images/EPLogos/nrg.jpg" },
  {  imgAlt: "TransUnion",  imgUrl: "./images/EPLogos/transunion.jpg" },
  {  imgAlt: "True Value Company",  imgUrl: "./images/EPLogos/truevalue.jpg" },
  {  imgAlt: "UL",  imgUrl: "./images/EPLogos/UL.png" },
  {  imgAlt: "United Airlines",  imgUrl: "./images/EPLogos/united.png" },
  {  imgAlt: "United Scrap Metal, Inc.",  imgUrl: "./images/EPLogos/unitedScrap.png" },
  {  imgAlt: "University of Illinois at Chicago (UIC)",  imgUrl: "./images/EPLogos/uic.png" },
  {  imgAlt: "Univision Chicago",  imgUrl: "./images/EPLogos/univision.png" },
  {  imgAlt: "US Foods",  imgUrl: "./images/EPLogos/US Foods Logo.jpg" },
  {  imgAlt: "WBEZ",  imgUrl: "./images/EPLogos/wbez.png" },
  {  imgAlt: "Women's Business Development Center",  imgUrl: "./images/EPLogos/wbdc.png" },
  {  imgAlt: "World Business Chicago",  imgUrl: "./images/EPLogos/wbc.png" },
  {  imgAlt: "WTTW WFMT",  imgUrl: "./images/EPLogos/wttw.png" },
  {  imgAlt: "YWCA Metropolitan Chicago",  imgUrl: "./images/EPLogos/ywca.jpg" },
  {  imgAlt: "Zeno Group",  imgUrl: "./images/EPLogos/zeno.png" },
  {  imgAlt: "Ziegler",  imgUrl: "./images/EPLogos/ziegler-logo.png" },

];

export const strategicPlanItems = [
  {
    img: "./images/strategicPlan/retain.svg",
    imgAlt: "",
    textContent: "<strong>Retain</strong> exclusivity, engagement, and high ROI for TCN members, while working purposefully toward having the diversity of the membership reflect the diversity of the professional women in the City"
  },
  {
    img: "./images/strategicPlan/serve.svg",
    imgAlt: "",
    textContent: ""
  },
  {
    img: "./images/strategicPlan/engage.svg",
    imgAlt: "",
    textContent: ""
  }
];
